### ISSUE TITLE
The dataflow score is 0

### ISSUE THREAD

**Issue by XiaoXiaoYi123** [k4black/codebleu#20]
WARNING:root:WARNING: There is no reference data-flows extracted from the whole corpus, and the data-flow match score degenerates to 0. Please consider ignoring this score.

I get this warning when I'm calculating, and I want to know why is this a problem

**Comment by k4black** [comment]
It is warning from the original implementation, so i can not consult on why dataflow works as it works =)

I can suggest you calc single example and get this warning. data flow designed to be applied to some corpus, not the single example.
