### ISSUE TITLE
Recived Typeerror

### ISSUE THREAD

**Issue by beishangeyu** [k4black/codebleu#61]
Hi
I run the flowing code
```python
codebleu = calc_codebleu([self.orig_code], [code], lang="python")["codebleu"]
```
And i receive a  Typeerror says an integer is required
The detailed log is as follows: 
```shell
  File "/root/adv/adv_attack/gene_sample_MBPP.py", line 177, in predict
    codebleu = calc_codebleu([self.orig_code], [code], lang="python")["codebleu"]
  File "/root/miniconda3/envs/adv/lib/python3.10/site-packages/codebleu/codebleu.py", line 41, in calc_codebleu
    tree_sitter_language = get_tree_sitter_language(lang)
  File "/root/miniconda3/envs/adv/lib/python3.10/site-packages/codebleu/utils.py", line 163, in get_tree_sitter_language
    return Language(tree_sitter_python.language())
TypeError: an integer is required
```
but my ussage is similar to the ussage in readme

when i just copy the usage in readme, i received the same error

**Comment by beishangeyu** [comment]
I fix this problem by installing codebleu from github

**Comment by PiXianDouBanJiang** [comment]
Hi I received the same error. Can you tell me the specific process that you solved this error?

**Comment by beishangeyu** [comment]
去codebleu的github仓库里，使用readme里边的那个git方法安装，不要直接使用pip安装。在这之前记得把本来pip安装的卸载掉

---- Replied Message ----
| From | ***@***.***> |
| Date | 09/09/2024 11:37 AM |
| To | k4black/codebleu ***@***.***> |
| Cc | 悲伤鳄鱼吃面包 ***@***.***>,
State ***@***.***> |
| Subject | Re: [k4black/codebleu] Recived Typeerror (Issue #61) |

Hi I received the same error. Can you tell me the specific process that you solved this error?

**Comment by PiXianDouBanJiang** [comment]
@beishangeyu 感谢！！
